### ISSUE TITLE
Error loading script: gelbooru_prompt.py

### ISSUE THREAD

**Issue by azefio** [antis0007/sd-webui-gelbooru-prompt#4]
Gelbooru prompt extension failed to load on my stable diffusion webui every time (v1.9.3)

I tried to install it in every way I know; manually, install from URL and Stability Matrix's extension list, Always the same error.

There's the console error message :

*** Error loading script: gelbooru_prompt.py
    Traceback (most recent call last):
      File "G:\Stability Matrix\Data\Packages\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "G:\Stability Matrix\Data\Packages\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "G:\Stability Matrix\Data\Packages\stable-diffusion-webui\extensions\sd-webui-gelbooru-prompt\scripts\gelbooru_prompt.py", line 11, in <module>
        import bs4
    ModuleNotFoundError: No module named 'bs4

**Comment by ElizaPottinger** [comment]
Easy fix:

Go the root folder where your SD tool is, like
`E:\Stability Matrix\Data\Packages\Stable Diffusion WebUI Forge`, it should have the `VENV` folder in it.
Open a CMD in that folder and type:
`venv/\Scripts\activate`
When you see: `(base) (venv) PS E:\Stability Matrix\Data\Packages\Stable Diffusion WebUI Forge>`, you know it is working.
Next step is: 
`pip install BeautifulSoup4`
Once you have done it, it should run.
![Untitled](https://github.com/antis0007/sd-webui-gelbooru-prompt/assets/111184250/a48a831d-1442-4b53-8d82-629001b2cc79)

**Comment by azefio** [comment]
How to open a CMD in folder ?

**Comment by ElizaPottinger** [comment]
you can either right click in the folder and choose open terminal or open the cmd normally and navigate to the folder with cd

**Comment by azefio** [comment]
"venv/\Scripts\activate" doesn't work.

**Comment by Inosss** [comment]
You need to install BeautifulSoup4 in local python folder.

We have 2 folders if we get Forge UI:
system
webui
environment.bat
run.bat
update.bat

we need go to "\system\python". Open CMD, write "cd " and copy here full path to this folder in quotes '    '
In my case this will be:      cd 'D:\SD\forge\system\python'

Than copy in CMD window this:

.\python.exe get-pip.py
.\python.exe -m pip install beautifulsoup4

Done.
