### ISSUE TITLE
Error calling

### ISSUE THREAD

**Issue by Damozgit** [antis0007/sd-webui-gelbooru-prompt#5]
Gelbooru prompt extension gives me an error message upon loading and is unusable in A1111

Error message:
*** Error calling: C:\A1111\webui\webui\extensions\sd-webui-gelbooru-prompt\scripts\gelbooru_prompt.py/ui
    Traceback (most recent call last):
      File "C:\A1111\webui\webui\modules\scripts.py", line 535, in wrap_call
        return func(*args, **kwargs)
      File "C:\A1111\webui\webui\extensions\sd-webui-gelbooru-prompt\scripts\gelbooru_prompt.py", line 67, in ui
        image = gr.File(type="filepath", label="Image with MD5 Hash")
      File "C:\A1111\webui\webui\venv\lib\site-packages\gradio\components\file.py", line 95, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: filepath. Please choose from one of: ['file', 'binary', 'bytes']

---
*** Error calling: C:\A1111\webui\webui\extensions\sd-webui-gelbooru-prompt\scripts\gelbooru_prompt.py/ui
    Traceback (most recent call last):
      File "C:\A1111\webui\webui\modules\scripts.py", line 535, in wrap_call
        return func(*args, **kwargs)
      File "C:\A1111\webui\webui\extensions\sd-webui-gelbooru-prompt\scripts\gelbooru_prompt.py", line 67, in ui
        image = gr.File(type="filepath", label="Image with MD5 Hash")
      File "C:\A1111\webui\webui\venv\lib\site-packages\gradio\components\file.py", line 95, in __init__
        raise ValueError(
    ValueError: Invalid value for parameter `type`: filepath. Please choose from one of: ['file', 'binary', 'bytes']

**Comment by TheRealAquaChicken** [comment]
I am getting the same issue now.
